disabled_rules:
  - trailing_whitespace
  - line_length
  - identifier_name

opt_in_rules:
  - empty_count
  - closure_spacing

excluded:
  - ${PWD}/.build
  - ${PWD}/Pods

identifier_name:
  min_length:
    warning: 1
    error: 1
  max_length:
    warning: 60
    error: 80
  excluded:
    - id
    - x
    - y
