name: ClipFlow
options:
  bundleIdPrefix: com.clipflow
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    SWIFT_VERSION: "5.9"

targets:
  ClipFlow:
    type: application
    platform: macOS
    sources:
      - path: Sources
        type: group
    resources:
      - path: Resources/Assets.xcassets
      - path: Resources/Assets.xcassets/AppIcon
      - path: Resources/ClipFlow.xcdatamodeld
      - path: Resources/Info.plist
      - path: Resources/ClipFlow.entitlements
      - path: Resources/en.lproj
        type: folder
      - path: Resources/zh-Hans.lproj
        type: folder
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.clipflow.app
        INFOPLIST_FILE: Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        COMBINE_HIDPI_IMAGES: YES
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_ENTITLEMENTS: Resources/ClipFlow.entitlements
    entitlements:
      path: Resources/ClipFlow.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.files.user-selected.read-only: true
        com.apple.security.network.client: true
    postBuildScripts:
      - name: SwiftLint
        script: |
          if which swiftlint > /dev/null; then
            swiftlint
          else
            echo "warning: SwiftLint not installed"
          fi
        basedOnDependencyAnalysis: false

schemes:
  ClipFlow:
    build:
      targets:
        ClipFlow: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
