name: ClipFlow
options:
  bundleIdPrefix: com.clipflow
  deploymentTarget:
    macOS: "15.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

packages:
  GRDB:
    url: https://github.com/groue/GRDB.swift
    from: 7.9.0
  OpenAI:
    url: https://github.com/MacPaw/OpenAI.git
    from: "0.4.7"
  KeychainAccess:
    url: https://github.com/kishikawakatsumi/KeychainAccess.git
    from: "4.2.2"
  MarkdownView:
    url: https://github.com/LiYanan2004/MarkdownView.git
    from: "2.4.0"
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle
    from: "2.6.0"

settings:
  base:
    MARKETING_VERSION: "1.0.11"
    CURRENT_PROJECT_VERSION: "12"
    DEVELOPMENT_TEAM: "7437GDF3XU"
    CODE_SIGN_STYLE: Manual
    CODE_SIGN_IDENTITY: "Developer ID Application: Deqiao Ding (7437GDF3XU)"
    CODE_SIGNING_REQUIRED: YES
    CODE_SIGNING_ALLOWED: YES
    CODE_SIGN_TIMESTAMP_SERVER: "timestamp.apple.com"
    SWIFT_VERSION: "6.0"

targets:
  ClipFlow:
    type: application
    platform: macOS
    sources:
      - path: Sources
        type: group
    dependencies:
      - package: GRDB
      - package: OpenAI
      - package: KeychainAccess
      - package: MarkdownView
      - package: Sparkle
    resources:
      - path: Resources/Assets.xcassets
      - path: Resources/en.lproj
        type: folder
      - path: Resources/zh-Hans.lproj
        type: folder
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.clipflow.app
        INFOPLIST_FILE: Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        COMBINE_HIDPI_IMAGES: YES
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_ENTITLEMENTS: Resources/ClipFlow.entitlements
    entitlements:
      path: Resources/ClipFlow.entitlements
    postBuildScripts:
      - name: SwiftLint
        script: |
          if which swiftlint > /dev/null; then
            swiftlint || true
          else
            echo "warning: SwiftLint not installed"
          fi
        basedOnDependencyAnalysis: false

schemes:
  ClipFlow:
    build:
      targets:
        ClipFlow: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
